import jwt
import requests
import json
import random
import uuid
from datetime import datetime, timedelta

# Configuration
API_URL = "https://todo-api-phase3.vercel.app"
USER_ID = "cli-agent-test-user"

def get_secret():
    print("To access the production API, I need the JWT_SECRET.")
    print("This should match the BETTER_AUTH_SECRET in your Vercel project.")
    return input("Enter JWT_SECRET: ").strip()

def generate_token(secret):
    payload = {
        'sub': USER_ID,
        'user_id': USER_ID,
        'exp': datetime.utcnow() + timedelta(hours=1),
        'iat': datetime.utcnow()
    }
    return jwt.encode(payload, secret, algorithm='HS256')

def run_test():
    try:
        secret = get_secret()
        if not secret:
            print("No secret provided. Exiting.")
            return

        token = generate_token(secret)
        headers = {
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json"
        }

        print(f"\nUsing API URL: {API_URL}")
        print(f"Test User ID: {USER_ID}")

        # 1. Create Task
        print("\n[1] Creating Random Task...")
        random_id = str(uuid.uuid4())[:8]
        new_task = {
            "title": f"Test Task {random_id}",
            "description": f"This is a random test task generated by CLI agent at {datetime.utcnow()}",
            "priority": random.choice(["High", "Medium", "Low"]),
            "tags": ["test", "cli-generated"]
        }
        
        response = requests.post(f"{API_URL}/tasks/", headers=headers, json=new_task)
        if response.status_code == 401:
            print("Error: 401 Unauthorized. The secret provided might be incorrect.")
            return
        if response.status_code != 200 and response.status_code != 201:
            print(f"Error creating task: {response.status_code} - {response.text}")
            return
            
        created_task = response.json()
        task_id = created_task['id']
        print(f"Success! Created Task ID: {task_id}")
        print(json.dumps(created_task, indent=2))

        # 2. Get Task
        print(f"\n[2] Fetching Task {task_id}...")
        response = requests.get(f"{API_URL}/tasks/{task_id}", headers=headers)
        if response.status_code != 200:
            print(f"Error fetching task: {response.status_code} - {response.text}")
            return
        print("Success! Task fetched.")

        # 3. Update Task
        print(f"\n[3] Updating Task {task_id}...")
        update_payload = {
            "title": f"Test Task {random_id} (UPDATED)"
        }
        response = requests.put(f"{API_URL}/tasks/{task_id}", headers=headers, json=update_payload)
        if response.status_code != 200:
            print(f"Error updating task: {response.status_code} - {response.text}")
            return
        
        updated_task = response.json()
        print("Success! Task title updated.")
        
        # 3.5 Toggle Completion
        print(f"\n[3.5] Toggling Task Completion...")
        response = requests.post(f"{API_URL}/tasks/{task_id}/toggle", headers=headers)
        if response.status_code != 200:
            print(f"Error toggling task: {response.status_code} - {response.text}")
            return
            
        toggled_task_response = response.json()
        final_task = toggled_task_response.get('task')
        print("Success! Task toggled.")
        print(json.dumps(final_task, indent=2))

        # 4. Verify Update
        if final_task['title'] == update_payload['title'] and final_task['completed'] == True:
            print("\nVERIFICATION PASSED: Task was correctly updated and completed.")
        else:
            print("\nVERIFICATION FAILED: Task data does not match update.")

    except Exception as e:
        print(f"\nAn error occurred: {e}")

if __name__ == "__main__":
    run_test()
